# Generated by Django 2.2.1 on 2019-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='title2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
