# Generated by Django 2.2.1 on 2019-08-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_page', '0002_auto_20190813_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
