# Generated by Django 2.2.1 on 2019-08-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog_image/', verbose_name='blog_image')),
                ('post', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
